rem REPO_NAME: PROJECTS_BAT
rem REPO_DIR=D:\PROJECTS_LYR\CHECK_LIST\03_SCRIPT\04_BAT\PROJECTS_BAT
rem ====================================================================

1.FreeFileSync:
---------------
D:\PROJECTS_LYR\CHECK_LIST\03_SCRIPT\04_BAT\PROJECTS_BAT\TOOLS_BAT\BAT
D:\PROJECTS_LYR\CHECK_LIST\03_SCRIPT\01_KIX\PROJECTS_KIX\TOOLS_KIX\BAT
->
D:\PROJECTS_LYR\CHECK_LIST\03_SCRIPT\01_KIX\TOOLS_KIX\BAT

2.FreeFileSync:
---------------
D:\PROJECTS_LYR\CHECK_LIST\03_SCRIPT\01_KIX\PROJECTS_KIX\TOOLS_KIX\LIB
->
D:\PROJECTS_LYR\CHECK_LIST\03_SCRIPT\01_KIX\TOOLS_KIX\LIB

3.git push PROJECTS_KIX:
---------------
call D:\PROJECTS_LYR\CHECK_LIST\03_SCRIPT\01_KIX\PROJECTS_KIX\lyrgit_push_main.bat

4.git push TOOLS_KIX:
---------------
call D:\PROJECTS_LYR\CHECK_LIST\03_SCRIPT\01_KIX\TOOLS_KIX\lyrgit_push_main.bat

5.git pull TOOLS_KIX:
---------------
D:\TOOLS\TOOLS_KIX
    git pull    
